import { FormEvent, useEffect, useState } from "react";
import { BarChart3, FileText, FolderKanban, LogOut, Mail, Plus, Settings, Sparkles, Trash2, Wrench } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Tab = "overview" | "services" | "projects" | "posts" | "contacts" | "settings";
const tabs: [Tab,string,typeof Wrench][] = [["overview","Overview",BarChart3],["services","Services",Wrench],["projects","Projects",FolderKanban],["posts","Journal",FileText],["contacts","Messages",Mail],["settings","Settings",Settings]];

export default function Admin() {
  const [session,setSession]=useState<any>(null); const [authorized,setAuthorized]=useState<boolean|null>(null); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [tab,setTab]=useState<Tab>("overview"); const [items,setItems]=useState<any[]>([]); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState("");
  useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_,s)=>setSession(s)); return ()=>subscription.unsubscribe();},[]);
  const login=async(e:FormEvent)=>{e.preventDefault();setBusy(true);const {error}=await supabase.auth.signInWithPassword({email,password});setNotice(error?.message||"");setBusy(false);};
  const load=async(table:string)=>{setBusy(true);const {data,error}=await supabase.from(table).select("*").order("created_at",{ascending:false});if(!error)setItems(data||[]);setBusy(false);};
  useEffect(()=>{ if (!session) { setAuthorized(null); return; } supabase.from("users").select("role").eq("id", session.user.id).maybeSingle().then(({data,error})=>{ const ok=!error && !!data && (data.role === "admin" || data.role === "editor"); setAuthorized(ok); if(!ok) setNotice("This account is not authorized for the admin workspace."); }); },[session]);
  useEffect(()=>{if(session && authorized && tab!=="overview")load(tab==="posts"?"blog_posts":tab);},[session,authorized,tab]);
  const addService=async()=>{const title=window.prompt("Service title");if(!title)return;await supabase.from("services").insert({title,slug:title.toLowerCase().replace(/[^a-z0-9]+/g,"-"),excerpt:"New service",description:"Describe this service from the admin dashboard."});load("services");};
  const remove=async(table:string,id:string)=>{await supabase.from(table).delete().eq("id",id);load(table);};
  if(!session)return <div className="grid min-h-screen place-items-center bg-[#090909] px-5 text-white"><form onSubmit={login} className="glass w-full max-w-md rounded-3xl p-8"><div className="mb-9 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full border border-[#d6b17d] text-[#d6b17d]">L</span><span className="text-sm font-bold tracking-[.2em]">LUMEN / ADMIN</span></div><h1 className="font-display text-5xl">Welcome back.</h1><p className="mt-3 text-sm text-[#a6a19a]">Sign in to manage your studio.</p><input required type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-10 w-full border-b border-white/15 bg-transparent py-3 text-sm outline-none focus:border-[#d6b17d]"/><input required type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-5 w-full border-b border-white/15 bg-transparent py-3 text-sm outline-none focus:border-[#d6b17d]"/><button disabled={busy} className="lumen-btn lumen-btn-primary mt-8 w-full">{busy?"Signing in…":"Enter dashboard"}</button>{notice&&<p className="mt-4 text-xs text-[#ee806f]">{notice}</p>}</form></div>;
  if (authorized === null) return <div className="grid min-h-screen place-items-center bg-[#090909] text-sm text-[#a6a19a]">Checking workspace access…</div>;
  if (!authorized) return <div className="grid min-h-screen place-items-center bg-[#090909] px-5 text-center text-white"><div><p className="text-[#ee806f]">{notice}</p><button onClick={()=>supabase.auth.signOut()} className="lumen-btn lumen-btn-ghost mt-6">Sign out</button></div></div>;
  return <div className="min-h-screen bg-[#090909] text-white"><aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-white/10 bg-[#0c0c0c] p-5 md:block"><div className="mb-14 flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full border border-[#d6b17d] text-[#d6b17d]">L</span><span className="text-xs font-bold tracking-[.2em]">LUMEN / ADMIN</span></div><nav className="grid gap-1">{tabs.map(([key,label,Icon])=><button key={key} onClick={()=>setTab(key)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition ${tab===key?'bg-white/10 text-white':'text-[#8c8881] hover:bg-white/5 hover:text-white'}`}><Icon size={16}/>{label}</button>)}</nav><button onClick={()=>supabase.auth.signOut()} className="absolute bottom-6 left-5 flex items-center gap-3 text-xs text-[#8c8881] hover:text-white"><LogOut size={15}/> Sign out</button></aside><main className="md:pl-64"><header className="flex h-20 items-center justify-between border-b border-white/10 px-5 md:px-10"><div><p className="eyebrow">Workspace</p><h1 className="text-lg font-semibold">{tabs.find(t=>t[0]===tab)?.[1]}</h1></div><button onClick={()=>supabase.auth.signOut()} className="md:hidden"><LogOut size={18}/></button></header><section className="p-5 md:p-10">{tab==="overview"?<Overview onNavigate={setTab}/>:<Manager tab={tab} items={items} busy={busy} addService={addService} remove={remove} load={load}/>}</section></main></div>;
}
function Overview({onNavigate}:{onNavigate:(t:Tab)=>void}){return <div><div className="mb-10 flex items-end justify-between"><div><p className="eyebrow mb-3">Good morning</p><h2 className="font-display text-5xl md:text-7xl">Your studio,<br/><span className="gradient-text">in motion.</span></h2></div><Sparkles className="hidden text-[#d6b17d] md:block" size={34}/></div><div className="grid gap-4 md:grid-cols-4">{[["services","Services","Shape the offer"],["projects","Projects","Show the work"],["posts","Journal","Share the thinking"],["contacts","Messages","Keep the loop open"]].map(([key,label,desc])=><button onClick={()=>onNavigate(key as Tab)} key={key} className="glass rounded-2xl p-6 text-left transition hover:-translate-y-1 hover:border-[#d6b17d]/60"><p className="text-xs text-[#a6a19a]">{desc}</p><p className="mt-10 text-2xl font-semibold">{label}</p><span className="mt-5 block text-xs text-[#d6b17d]">Manage →</span></button>)}</div></div>}
function Manager({tab,items,busy,addService,remove,load}:{tab:Tab;items:any[];busy:boolean;addService:()=>void;remove:(table:string,id:string)=>void;load:(table:string)=>void}){const table=tab==="posts"?"blog_posts":tab;return <div><div className="mb-7 flex items-center justify-between"><div><p className="eyebrow">Content management</p><h2 className="mt-2 font-display text-4xl">{tab[0].toUpperCase()+tab.slice(1)}</h2></div>{(tab==="services"||tab==="projects"||tab==="posts")&&<button onClick={tab==="services"?addService:()=>alert("Use the structured editor to add content.")} className="lumen-btn lumen-btn-primary"><Plus size={15}/> Add new</button>}</div><div className="glass overflow-hidden rounded-2xl">{busy?<div className="p-10 text-sm text-[#a6a19a]">Loading workspace…</div>:items.length===0?<div className="p-10 text-center text-sm text-[#a6a19a]">No records yet. Create the first one to get started.</div>:<div className="divide-y divide-white/10">{items.map(item=><div key={item.id} className="flex items-center justify-between gap-4 p-5"><div><p className="font-semibold">{item.title||item.name||item.email}</p><p className="mt-1 text-xs text-[#8c8881]">{item.slug||item.status||item.created_at}</p></div>{tab!=="settings"&&<button onClick={()=>remove(table,item.id)} className="text-[#8c8881] transition hover:text-[#ee806f]"><Trash2 size={16}/></button>}</div>)}</div>}</div></div>}
