import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, ArrowUpRight, Check, Loader2, Send } from "lucide-react";
import { Link, useLocation, useParams } from "wouter";
import { PageIntro, SiteShell } from "@/components/SiteShell";
import { useLanguage } from "@/contexts/LanguageContext";
import { createContact, getPost, getPosts, getProject, getProjects, getServices, BlogPost, Project, Service } from "@/lib/supabase";

function ErrorNote({ message }: { message: string }) { return message ? <div role="alert" className="lumen-container pt-8 text-sm text-[#ee806f]">{message}</div> : null; }
function EmptyNote({ message }: { message: string }) { return <div className="lumen-container py-16 text-center text-sm text-[#8c8881]">{message}</div>; }

type LocalizedRecord = { translations?: Record<string, Record<string, string>> | null };
function localized<T>(record: T, locale: string, field: string, fallback = "") { const translations = (record as T & LocalizedRecord).translations; return translations?.[locale]?.[field] || translations?.en?.[field] || fallback; }

function useMeta(title?: string, description?: string, image?: string) {
  useEffect(() => {
    if (!title) return;
    document.title = `${title} — Production Advertising`;
    const set = (name: string, content?: string) => { if (!content) return; let node = document.querySelector(`meta[name="${name}"]`) || document.querySelector(`meta[property="${name}"]`); if (!node) { node = document.createElement("meta"); node.setAttribute(name.startsWith("og:") ? "property" : "name", name); document.head.appendChild(node); } node.setAttribute("content", content); };
    set("description", description); set("og:title", title); set("og:description", description); set("og:image", image);
  }, [title, description, image]);
}

const fallbackServices: Service[] = []; /* Supabase is the only content source. */

export function About() { const { t } = useLanguage(); useMeta("Production Advertising", "A creative production studio for films, identities, and digital worlds."); return <SiteShell><PageIntro eyebrow={t("about")} title={<>A small studio<br/><span className="gradient-text italic">{t("aboutTitle")}</span></>} description={t("aboutDescription")}/><section className="lumen-container grid gap-16 py-28 md:grid-cols-12"><div className="md:col-span-5"><p className="eyebrow">{t("pointOfView")}</p></div><div className="md:col-span-7"><p className="font-display text-4xl leading-tight md:text-6xl">The work gets better when the question gets better.</p><p className="mt-8 max-w-xl text-base leading-8 text-[#a6a19a]">We believe the most memorable work is both precise and alive. It knows what it is saying, but leaves enough room for people to feel something of their own.</p></div></section><section className="border-y border-white/10 bg-[#111] py-20"><div className="lumen-container grid gap-4 md:grid-cols-3">{[['01','Curious by default'],['02','Craft is a point of view'],['03','Good work feels human']].map(([n,t])=><div className="glass rounded-2xl p-7" key={n}><span className="font-mono text-xs text-[#d6b17d]">{n}</span><h3 className="mt-16 text-xl font-semibold">{t}</h3></div>)}</div></section></SiteShell>; }

export function Services() { const { locale, t } = useLanguage(); useMeta("Services", "Creative production, identity, and digital experiences by Production Advertising."); const [items,setItems]=useState<Service[]>([]); const [error,setError]=useState(""); useEffect(()=>{getServices().then(data=>setItems(data)).catch(()=>setError(t("unableServices")));},[]); return <SiteShell><PageIntro eyebrow={t("capabilities")} title={<>The right kind<br/><span className="text-[#a6a19a]">of attention.</span></>} description="From a single frame to a full world, we help ambitious teams make work people can feel."/><ErrorNote message={error}/>{!error&&items.length===0?<EmptyNote message={t("noServices")}/>:<section className="lumen-container py-20">{items.map((s,i)=><Link href={`/services/${s.slug}`} key={s.id} className="group flex flex-col justify-between gap-6 border-b border-white/10 py-10 transition hover:border-[#d6b17d] md:flex-row md:items-center"><div className="flex items-start gap-7"><span className="font-mono text-xs text-[#d6b17d]">0{i+1}</span><div><h2 className="font-display text-4xl md:text-6xl">{localized(s, locale, "title", s.title)}</h2><p className="mt-3 max-w-md text-sm text-[#a6a19a]">{localized(s, locale, "excerpt", s.excerpt || "")}</p></div></div><span className="grid h-12 w-12 place-items-center rounded-full border border-white/10 transition group-hover:bg-[#f4f0e9] group-hover:text-black"><ArrowUpRight size={18}/></span></Link>)}</section>}</SiteShell>; }

export function Work() { const { locale, t } = useLanguage(); useMeta("Selected Work", "Films, identities, and digital experiences from Production Advertising."); const [items,setItems]=useState<Project[]>([]); const [error,setError]=useState(""); useEffect(()=>{getProjects().then(data=>setItems(data)).catch(()=>setError(t("unableProjects")));},[]); return <SiteShell><PageIntro eyebrow={t("selectedWork")} title={<>Built to be<br/><span className="gradient-text italic">remembered.</span></>} description={t("aFewThings")}/><ErrorNote message={error}/>{!error&&items.length===0?<EmptyNote message={t("noProjects")}/>:<section className="lumen-container grid gap-5 py-20 md:grid-cols-2">{items.map((p,i)=><Link href={`/work/${p.slug}`} key={p.id} className={`group ${i%3===1?'md:mt-20':''}`}><div className="relative aspect-[4/3] overflow-hidden rounded-2xl border border-white/10"><img src={p.cover_url} alt={p.title} loading="lazy" className="h-full w-full object-cover opacity-80 transition duration-700 group-hover:scale-105 group-hover:opacity-100"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent"/><div className="absolute bottom-5 left-5"><p className="eyebrow mb-2">{p.execution_date || 'Selected project'}</p><h2 className="text-2xl font-semibold">{localized(p, locale, "title", p.title)}</h2></div></div></Link>)}</section>}</SiteShell>; }

export function ProjectDetail() { const { locale, t } = useLanguage(); const { slug='' }=useParams<{slug:string}>(); const [project,setProject]=useState<Project|null>(null); const [error,setError]=useState(""); useMeta(project?.title, project?.description, project?.cover_url); useEffect(()=>{getProject(slug).then(data=>data&&setProject(data)).catch(()=>setError("Unable to load this project."));},[slug]); if(!project)return <SiteShell><PageIntro eyebrow="Project" title={error?"Unable to load project":t("projectNotFound")}/><ErrorNote message={error}/></SiteShell>; return <SiteShell><section className="lumen-container py-20 md:py-28"><Link href="/work" className="mb-12 inline-flex items-center gap-2 text-xs text-[#a6a19a] hover:text-white"><ArrowLeft size={14}/> {t("back")}</Link><p className="eyebrow mb-5">{project.execution_date || 'Project'} · {project.client?.name || 'Independent'}</p><h1 className="max-w-5xl font-display text-6xl leading-[.9] md:text-9xl">{localized(project, locale, "title", project.title)}</h1><p className="mt-8 max-w-xl text-lg leading-8 text-[#a6a19a]">{localized(project, locale, "description", project.description || "")}</p><img src={project.cover_url} alt={project.title} className="mt-16 aspect-video w-full rounded-3xl object-cover"/>{project.video_url && <video controls preload="metadata" className="mt-6 aspect-video w-full rounded-3xl border border-white/10"><source src={project.video_url} /></video>}{project.gallery && project.gallery.length > 0 && <div className="mt-6 grid gap-5 md:grid-cols-2">{project.gallery.map((asset, index) => <img key={asset.url || index} src={asset.url} alt={`${project.title} — ${index + 1}`} loading="lazy" className="aspect-[4/3] w-full rounded-2xl object-cover" />)}</div>}<div className="mt-12 grid gap-10 border-b border-white/10 pb-12 md:grid-cols-3"><div><p className="eyebrow mb-3">{t("servicesLabel")}</p><p className="text-sm text-[#a6a19a]">{project.services_used?.join(' · ') || 'Creative production'}</p></div><div><p className="eyebrow mb-3">{t("clientLabel")}</p><p className="text-sm text-[#a6a19a]">{project.client?.name || 'Confidential'}</p></div><div><p className="eyebrow mb-3">{t("categoryLabel")}</p><p className="text-sm text-[#a6a19a]">{project.category?.name || 'Featured work'}</p></div></div></section></SiteShell>; }

export function Journal() { const { locale, t } = useLanguage(); useMeta("Journal", "Field notes and references from the Production Advertising process."); const [posts,setPosts]=useState<BlogPost[]>([]); const [error,setError]=useState(""); useEffect(()=>{getPosts().then(data=>setPosts(data)).catch(()=>setError(t("unablePosts")));},[]); return <SiteShell><PageIntro eyebrow={t("journal")} title={<>Notes from<br/><span className="text-[#a6a19a]">{t("journalTitle")}</span></>} description={t("readNote")}/><ErrorNote message={error}/>{!error&&posts.length===0?<EmptyNote message={t("noPosts")}/>:<section className="lumen-container grid gap-6 py-20 md:grid-cols-2">{posts.map((p,i)=><Link href={`/journal/${p.slug}`} key={p.id} className={`group ${i===0?'md:col-span-2':''}`}><div className="grid gap-7 border-b border-white/10 pb-8 md:grid-cols-2"><div className="overflow-hidden rounded-2xl"><img src={p.cover_url} alt={p.title} loading="lazy" className="aspect-[16/9] w-full object-cover opacity-80 transition duration-700 group-hover:scale-105"/></div><div className="flex flex-col justify-between py-2"><div><p className="eyebrow mb-4">{p.published_at || 'Field note'}</p><h2 className="font-display text-4xl md:text-5xl">{localized(p, locale, "title", p.title)}</h2><p className="mt-5 text-sm leading-7 text-[#a6a19a]">{localized(p, locale, "excerpt", p.excerpt || "")}</p></div><span className="mt-7 flex items-center gap-2 text-xs text-[#d6b17d]">{t("readNote")} <ArrowUpRight size={14}/></span></div></div></Link>)}</section>}</SiteShell>; }

export function PostDetail() { const { locale, t } = useLanguage(); const { slug='' }=useParams<{slug:string}>(); const [post,setPost]=useState<BlogPost|null>(null); const [error,setError]=useState(""); useMeta(post?.meta_title || post?.title, post?.meta_description || post?.excerpt, post?.og_image_url || post?.cover_url); useEffect(()=>{getPost(slug).then(data=>data&&setPost(data)).catch(()=>setError("Unable to load this journal post."));},[slug]); if(!post)return <SiteShell><PageIntro eyebrow={t("journal")} title={error?"Unable to load note":t("noteNotFound")}/><ErrorNote message={error}/></SiteShell>; return <SiteShell><article className="lumen-container max-w-4xl py-20 md:py-28"><Link href="/journal" className="mb-12 inline-flex items-center gap-2 text-xs text-[#a6a19a] hover:text-white"><ArrowLeft size={14}/> {t("back")}</Link><p className="eyebrow mb-5">{post.published_at || 'Field note'}</p><h1 className="font-display text-6xl leading-[.95] md:text-8xl">{localized(post, locale, "title", post.title)}</h1><p className="mt-8 text-xl leading-8 text-[#a6a19a]">{localized(post, locale, "excerpt", post.excerpt || "")}</p><img src={post.cover_url} alt={post.title} className="mt-14 aspect-video w-full rounded-3xl object-cover"/><div className="prose prose-invert mt-14 max-w-2xl text-base leading-8 text-[#c6c0b7]"><p>{localized(post, locale, "content", post.content)}</p></div></article></SiteShell>; }

export function Contact() { const { t } = useLanguage(); useMeta("Production Advertising", "Start a conversation about your next project.");
  const [sent, setSent] = useState(false);
  const [loading, setLoading] = useState(false);
  const submit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    const form = new FormData(e.currentTarget);
    try {
      await createContact({ name: String(form.get('name')), email: String(form.get('email')), phone: String(form.get('phone') || ''), message: String(form.get('message')) });
      setSent(true);
      e.currentTarget.reset();
    } finally { setLoading(false); }
  };
  return <SiteShell>
    <PageIntro eyebrow={t("startConversation")} title={<>Tell us what<br/><span className="gradient-text italic">you’re imagining.</span></>} description={t("makeSomethingLast")} />
    <section className="lumen-container grid gap-16 py-20 md:grid-cols-12">
      <div className="md:col-span-4"><p className="eyebrow mb-6">Contact</p><p className="text-sm leading-7 text-[#a6a19a]">For collaborations, new business, or a hello from the other side of the world.</p><a className="mt-8 block text-lg text-[#d6b17d]" href="mailto:hello@lumen.studio">hello@lumen.studio</a></div>
      <form onSubmit={submit} className="glass rounded-3xl p-7 md:col-span-8 md:p-10">
        {sent ? <div className="flex min-h-72 flex-col items-center justify-center text-center"><span className="mb-5 grid h-14 w-14 place-items-center rounded-full bg-[#94cbb6] text-black"><Check /></span><h2 className="font-display text-4xl">{t("sentMessage")}</h2><p className="mt-3 text-sm text-[#a6a19a]">We’ll be in touch soon.</p></div> : <>
          <div className="grid gap-6 md:grid-cols-2"><label className="text-xs text-[#a6a19a]">{t("contactName")}<input required name="name" className="mt-2 w-full border-b border-white/15 bg-transparent py-3 text-base text-white outline-none focus:border-[#d6b17d]" /></label><label className="text-xs text-[#a6a19a]">{t("contactEmail")}<input required type="email" name="email" className="mt-2 w-full border-b border-white/15 bg-transparent py-3 text-base text-white outline-none focus:border-[#d6b17d]" /></label></div>
          <label className="mt-8 block text-xs text-[#a6a19a]">{t("contactPhone")}<input name="phone" className="mt-2 w-full border-b border-white/15 bg-transparent py-3 text-base text-white outline-none focus:border-[#d6b17d]" /></label>
          <label className="mt-8 block text-xs text-[#a6a19a]">{t("contactMessage")}<textarea required name="message" rows={4} className="mt-2 w-full resize-none border-b border-white/15 bg-transparent py-3 text-base text-white outline-none focus:border-[#d6b17d]" /></label>
          <button disabled={loading} className="lumen-btn lumen-btn-primary mt-9">{loading ? <Loader2 className="animate-spin" size={15} /> : <Send size={15} />} {t("sendMessage")}</button>
        </>}
      </form>
    </section>
  </SiteShell>;
}



export function ServiceDetail() { const { locale, t } = useLanguage();
  const { slug = '' } = useParams<{ slug: string }>();
  const [service, setService] = useState<Service | null>(null);
  useEffect(() => { getServices().then((items) => { const match = items.find((item) => item.slug === slug); if (match) setService(match); }).catch(() => {}); }, [slug]);
  if (!service) return <SiteShell><PageIntro eyebrow={t("services")} title={t("serviceNotFound")} /></SiteShell>;
  return <SiteShell><section className="lumen-container py-20 md:py-28"><Link href="/services" className="mb-12 inline-flex items-center gap-2 text-xs text-[#a6a19a] hover:text-white"><ArrowLeft size={14}/> {t("back")}</Link><p className="eyebrow mb-5">Capability · Lumen Studio</p><h1 className="max-w-4xl font-display text-6xl leading-[.9] md:text-9xl">{localized(service, locale, "title", service.title)}</h1><div className="mt-14 grid gap-10 border-t border-white/10 pt-10 md:grid-cols-3"><p className="text-xl leading-8 text-[#d6b17d]">{localized(service, locale, "excerpt", service.excerpt || "")}</p><p className="text-base leading-8 text-[#a6a19a] md:col-span-2">{localized(service, locale, "description", service.description || "")}</p></div><Link href="/contact" className="lumen-btn lumen-btn-primary mt-14">{t("startConversation")} <ArrowUpRight size={15}/></Link></section></SiteShell>;
}
