import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, ArrowUpRight, Check, Loader2, Send } from "lucide-react";
import { Link, useLocation, useParams } from "wouter";
import { PageIntro, SiteShell } from "@/components/SiteShell";
import { createContact, getPost, getPosts, getProject, getProjects, getServices, BlogPost, Project, Service } from "@/lib/supabase";

function useMeta(title?: string, description?: string, image?: string) {
  useEffect(() => {
    if (!title) return;
    document.title = `${title} — Lumen Studio`;
    const set = (name: string, content?: string) => { if (!content) return; let node = document.querySelector(`meta[name="${name}"]`) || document.querySelector(`meta[property="${name}"]`); if (!node) { node = document.createElement("meta"); node.setAttribute(name.startsWith("og:") ? "property" : "name", name); document.head.appendChild(node); } node.setAttribute("content", content); };
    set("description", description); set("og:title", title); set("og:description", description); set("og:image", image);
  }, [title, description, image]);
}

const fallbackServices: Service[] = [
  { id:'1', title:'Brand films', slug:'brand-films', excerpt:'A point of view, in motion.', description:'From first frame to final cut, we create films with an emotional center and a visual language that stays with you.', accent:'#d6b17d' },
  { id:'2', title:'Visual identity', slug:'visual-identity', excerpt:'Make it recognizable before it’s understood.', description:'Identity systems with enough flexibility to move across every touchpoint without losing their soul.', accent:'#94cbb6' },
  { id:'3', title:'Digital experiences', slug:'digital-experiences', excerpt:'Interfaces that feel like places.', description:'Websites and digital worlds designed with a sense of rhythm, clarity, and a little bit of wonder.', accent:'#ee806f' },
  { id:'4', title:'Creative direction', slug:'creative-direction', excerpt:'The thread that holds it together.', description:'A senior creative partner from the first question to the final detail.', accent:'#c6a5d9' },
];
const fallbackProjects: Project[] = [
  { id:'1', title:'Afterlight', slug:'afterlight', description:'A film about the quiet electricity between people, places, and the moments we almost miss.', cover_url:'https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?auto=format&fit=crop&w=1600&q=85', gallery:[], services_used:['Brand film','Creative direction'], execution_date:'2025' },
  { id:'2', title:'Noma', slug:'noma', description:'A visual language for movement, made to live between stillness and speed.', cover_url:'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1600&q=85', gallery:[], services_used:['Campaign','Digital experience'], execution_date:'2024' },
  { id:'3', title:'Vela', slug:'vela', description:'An identity for the long way: warm, tactile, and deliberately unhurried.', cover_url:'https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&w=1600&q=85', gallery:[], services_used:['Identity','Art direction'], execution_date:'2024' },
];
const fallbackPosts: BlogPost[] = [
  { id:'1', title:'The value of a slower first draft', slug:'slower-first-draft', excerpt:'Why the most useful thing in a creative process is often the space before the answer.', content:'The best ideas rarely arrive fully formed. They arrive as a question, a texture, a feeling you can’t quite name yet. A slower first draft gives those signals room to become something with a pulse.', cover_url:'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1400&q=85', published_at:'2025-09-12' },
  { id:'2', title:'Making room for the unexpected', slug:'room-for-the-unexpected', excerpt:'A small field note on collaboration, curiosity, and leaving the door open.', content:'Creative work is a conversation with the unexpected. Structure helps us move, but openness is what lets the work surprise us.', cover_url:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1400&q=85', published_at:'2025-07-03' },
];

export function About() { return <SiteShell><PageIntro eyebrow="About Lumen" title={<>A small studio<br/><span className="gradient-text italic">with a wide lens.</span></>} description="We are a loose constellation of directors, designers, strategists, and makers. Small enough to care about every detail. Experienced enough to know which details matter."/><section className="lumen-container grid gap-16 py-28 md:grid-cols-12"><div className="md:col-span-5"><p className="eyebrow">Our point of view</p></div><div className="md:col-span-7"><p className="font-display text-4xl leading-tight md:text-6xl">The work gets better when the question gets better.</p><p className="mt-8 max-w-xl text-base leading-8 text-[#a6a19a]">We believe the most memorable work is both precise and alive. It knows what it is saying, but leaves enough room for people to feel something of their own.</p></div></section><section className="border-y border-white/10 bg-[#111] py-20"><div className="lumen-container grid gap-4 md:grid-cols-3">{[['01','Curious by default'],['02','Craft is a point of view'],['03','Good work feels human']].map(([n,t])=><div className="glass rounded-2xl p-7" key={n}><span className="font-mono text-xs text-[#d6b17d]">{n}</span><h3 className="mt-16 text-xl font-semibold">{t}</h3></div>)}</div></section></SiteShell>; }

export function Services() { const [items,setItems]=useState<Service[]>(fallbackServices); useEffect(()=>{getServices().then(data=>data.length&&setItems(data)).catch(()=>{});},[]); return <SiteShell><PageIntro eyebrow="Capabilities" title={<>The right kind<br/><span className="text-[#a6a19a]">of attention.</span></>} description="From a single frame to a full world, we help ambitious teams make work people can feel."/><section className="lumen-container py-20">{items.map((s,i)=><Link href={`/services/${s.slug}`} key={s.id} className="group flex flex-col justify-between gap-6 border-b border-white/10 py-10 transition hover:border-[#d6b17d] md:flex-row md:items-center"><div className="flex items-start gap-7"><span className="font-mono text-xs text-[#d6b17d]">0{i+1}</span><div><h2 className="font-display text-4xl md:text-6xl">{s.title}</h2><p className="mt-3 max-w-md text-sm text-[#a6a19a]">{s.excerpt}</p></div></div><span className="grid h-12 w-12 place-items-center rounded-full border border-white/10 transition group-hover:bg-[#f4f0e9] group-hover:text-black"><ArrowUpRight size={18}/></span></Link>)}</section></SiteShell>; }

export function Work() { const [items,setItems]=useState<Project[]>(fallbackProjects); useEffect(()=>{getProjects().then(data=>data.length&&setItems(data)).catch(()=>{});},[]); return <SiteShell><PageIntro eyebrow="Selected work" title={<>Built to be<br/><span className="gradient-text italic">remembered.</span></>} description="A selection of films, identities, and digital experiences made alongside people we admire."/><section className="lumen-container grid gap-5 py-20 md:grid-cols-2">{items.map((p,i)=><Link href={`/work/${p.slug}`} key={p.id} className={`group ${i%3===1?'md:mt-20':''}`}><div className="relative aspect-[4/3] overflow-hidden rounded-2xl border border-white/10"><img src={p.cover_url} alt={p.title} loading="lazy" className="h-full w-full object-cover opacity-80 transition duration-700 group-hover:scale-105 group-hover:opacity-100"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent"/><div className="absolute bottom-5 left-5"><p className="eyebrow mb-2">{p.execution_date || 'Selected project'}</p><h2 className="text-2xl font-semibold">{p.title}</h2></div></div></Link>)}</section></SiteShell>; }

export function ProjectDetail() { const { slug='' }=useParams<{slug:string}>(); const [project,setProject]=useState<Project|null>(fallbackProjects.find(p=>p.slug===slug)||null); useMeta(project?.title, project?.description, project?.cover_url); useEffect(()=>{getProject(slug).then(data=>data&&setProject(data)).catch(()=>{});},[slug]); if(!project)return <SiteShell><PageIntro eyebrow="Project" title="Project not found"/></SiteShell>; return <SiteShell><section className="lumen-container py-20 md:py-28"><Link href="/work" className="mb-12 inline-flex items-center gap-2 text-xs text-[#a6a19a] hover:text-white"><ArrowLeft size={14}/> Back to work</Link><p className="eyebrow mb-5">{project.execution_date || 'Project'} · {project.client?.name || 'Independent'}</p><h1 className="max-w-5xl font-display text-6xl leading-[.9] md:text-9xl">{project.title}</h1><p className="mt-8 max-w-xl text-lg leading-8 text-[#a6a19a]">{project.description}</p><img src={project.cover_url} alt={project.title} className="mt-16 aspect-video w-full rounded-3xl object-cover"/>{project.video_url && <video controls preload="metadata" className="mt-6 aspect-video w-full rounded-3xl border border-white/10"><source src={project.video_url} /></video>}{project.gallery && project.gallery.length > 0 && <div className="mt-6 grid gap-5 md:grid-cols-2">{project.gallery.map((asset, index) => <img key={asset.url || index} src={asset.url} alt={`${project.title} — ${index + 1}`} loading="lazy" className="aspect-[4/3] w-full rounded-2xl object-cover" />)}</div>}<div className="mt-12 grid gap-10 border-b border-white/10 pb-12 md:grid-cols-3"><div><p className="eyebrow mb-3">Services</p><p className="text-sm text-[#a6a19a]">{project.services_used?.join(' · ') || 'Creative production'}</p></div><div><p className="eyebrow mb-3">Client</p><p className="text-sm text-[#a6a19a]">{project.client?.name || 'Confidential'}</p></div><div><p className="eyebrow mb-3">Category</p><p className="text-sm text-[#a6a19a]">{project.category?.name || 'Featured work'}</p></div></div></section></SiteShell>; }

export function Journal() { const [posts,setPosts]=useState<BlogPost[]>(fallbackPosts); useEffect(()=>{getPosts().then(data=>data.length&&setPosts(data)).catch(()=>{});},[]); return <SiteShell><PageIntro eyebrow="Journal" title={<>Notes from<br/><span className="text-[#a6a19a]">the process.</span></>} description="Field notes, references, and honest thoughts on making things with care."/><section className="lumen-container grid gap-6 py-20 md:grid-cols-2">{posts.map((p,i)=><Link href={`/journal/${p.slug}`} key={p.id} className={`group ${i===0?'md:col-span-2':''}`}><div className="grid gap-7 border-b border-white/10 pb-8 md:grid-cols-2"><div className="overflow-hidden rounded-2xl"><img src={p.cover_url} alt={p.title} loading="lazy" className="aspect-[16/9] w-full object-cover opacity-80 transition duration-700 group-hover:scale-105"/></div><div className="flex flex-col justify-between py-2"><div><p className="eyebrow mb-4">{p.published_at || 'Field note'}</p><h2 className="font-display text-4xl md:text-5xl">{p.title}</h2><p className="mt-5 text-sm leading-7 text-[#a6a19a]">{p.excerpt}</p></div><span className="mt-7 flex items-center gap-2 text-xs text-[#d6b17d]">Read note <ArrowUpRight size={14}/></span></div></div></Link>)}</section></SiteShell>; }

export function PostDetail() { const { slug='' }=useParams<{slug:string}>(); const [post,setPost]=useState<BlogPost|null>(fallbackPosts.find(p=>p.slug===slug)||null); useMeta(post?.meta_title || post?.title, post?.meta_description || post?.excerpt, post?.og_image_url || post?.cover_url); useEffect(()=>{getPost(slug).then(data=>data&&setPost(data)).catch(()=>{});},[slug]); if(!post)return <SiteShell><PageIntro eyebrow="Journal" title="Note not found"/></SiteShell>; return <SiteShell><article className="lumen-container max-w-4xl py-20 md:py-28"><Link href="/journal" className="mb-12 inline-flex items-center gap-2 text-xs text-[#a6a19a] hover:text-white"><ArrowLeft size={14}/> Back to journal</Link><p className="eyebrow mb-5">{post.published_at || 'Field note'}</p><h1 className="font-display text-6xl leading-[.95] md:text-8xl">{post.title}</h1><p className="mt-8 text-xl leading-8 text-[#a6a19a]">{post.excerpt}</p><img src={post.cover_url} alt={post.title} className="mt-14 aspect-video w-full rounded-3xl object-cover"/><div className="prose prose-invert mt-14 max-w-2xl text-base leading-8 text-[#c6c0b7]"><p>{post.content}</p></div></article></SiteShell>; }

export function Contact() {
  const [sent, setSent] = useState(false);
  const [loading, setLoading] = useState(false);
  const submit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    const form = new FormData(e.currentTarget);
    try {
      await createContact({ name: String(form.get('name')), email: String(form.get('email')), phone: String(form.get('phone') || ''), message: String(form.get('message')) });
      setSent(true);
      e.currentTarget.reset();
    } finally { setLoading(false); }
  };
  return <SiteShell>
    <PageIntro eyebrow="Start a conversation" title={<>Tell us what<br/><span className="gradient-text italic">you’re imagining.</span></>} description="The good stuff usually starts with a hello. Tell us a little about the challenge, the ambition, or the question." />
    <section className="lumen-container grid gap-16 py-20 md:grid-cols-12">
      <div className="md:col-span-4"><p className="eyebrow mb-6">Contact</p><p className="text-sm leading-7 text-[#a6a19a]">For collaborations, new business, or a hello from the other side of the world.</p><a className="mt-8 block text-lg text-[#d6b17d]" href="mailto:hello@lumen.studio">hello@lumen.studio</a></div>
      <form onSubmit={submit} className="glass rounded-3xl p-7 md:col-span-8 md:p-10">
        {sent ? <div className="flex min-h-72 flex-col items-center justify-center text-center"><span className="mb-5 grid h-14 w-14 place-items-center rounded-full bg-[#94cbb6] text-black"><Check /></span><h2 className="font-display text-4xl">Message received.</h2><p className="mt-3 text-sm text-[#a6a19a]">We’ll be in touch soon.</p></div> : <>
          <div className="grid gap-6 md:grid-cols-2"><label className="text-xs text-[#a6a19a]">Name<input required name="name" className="mt-2 w-full border-b border-white/15 bg-transparent py-3 text-base text-white outline-none focus:border-[#d6b17d]" /></label><label className="text-xs text-[#a6a19a]">Email<input required type="email" name="email" className="mt-2 w-full border-b border-white/15 bg-transparent py-3 text-base text-white outline-none focus:border-[#d6b17d]" /></label></div>
          <label className="mt-8 block text-xs text-[#a6a19a]">Phone<input name="phone" className="mt-2 w-full border-b border-white/15 bg-transparent py-3 text-base text-white outline-none focus:border-[#d6b17d]" /></label>
          <label className="mt-8 block text-xs text-[#a6a19a]">Tell us about it<textarea required name="message" rows={4} className="mt-2 w-full resize-none border-b border-white/15 bg-transparent py-3 text-base text-white outline-none focus:border-[#d6b17d]" /></label>
          <button disabled={loading} className="lumen-btn lumen-btn-primary mt-9">{loading ? <Loader2 className="animate-spin" size={15} /> : <Send size={15} />} Send message</button>
        </>}
      </form>
    </section>
  </SiteShell>;
}



export function ServiceDetail() {
  const { slug = '' } = useParams<{ slug: string }>();
  const [service, setService] = useState<Service | null>(fallbackServices.find((item) => item.slug === slug) || null);
  useEffect(() => { getServices().then((items) => { const match = items.find((item) => item.slug === slug); if (match) setService(match); }).catch(() => {}); }, [slug]);
  if (!service) return <SiteShell><PageIntro eyebrow="Service" title="Service not found" /></SiteShell>;
  return <SiteShell><section className="lumen-container py-20 md:py-28"><Link href="/services" className="mb-12 inline-flex items-center gap-2 text-xs text-[#a6a19a] hover:text-white"><ArrowLeft size={14}/> Back to services</Link><p className="eyebrow mb-5">Capability · Lumen Studio</p><h1 className="max-w-4xl font-display text-6xl leading-[.9] md:text-9xl">{service.title}</h1><div className="mt-14 grid gap-10 border-t border-white/10 pt-10 md:grid-cols-3"><p className="text-xl leading-8 text-[#d6b17d]">{service.excerpt}</p><p className="text-base leading-8 text-[#a6a19a] md:col-span-2">{service.description}</p></div><Link href="/contact" className="lumen-btn lumen-btn-primary mt-14">Talk about a project <ArrowUpRight size={15}/></Link></section></SiteShell>;
}
