import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from "react";

export type Locale = "ar" | "fr" | "en";

type TranslationKey = keyof typeof translations.en;

const translations = {
  en: {
    brand: "PRODUCTION / ADVERTISING",
    work: "Work", services: "Services", journal: "Journal", about: "About", contact: "Start a project",
    admin: "Admin", language: "Language", menu: "Toggle menu", footer: "Independent creative production for brands that want to be remembered.",
    copyright: "© 2026 Production Advertising", directionNote: "Stories with a pulse.", loading: "Loading Production…",
    homeEyebrow: "INDEPENDENT CREATIVE STUDIO · 01—26", homeTitle: "We make meaningful moves.",
    homeDescription: "Production is a creative studio shaping films, identities, and digital worlds for people building what comes next.",
    explore: "Explore the work", pointOfView: "Our point of view", scroll: "Scroll to explore ↓", newPerspectives: "NEW PERSPECTIVES, ALWAYS", selectedWork: "Selected work", aFewThings: "A few things we’ve made.", viewAll: "View all projects", whatWeDo: "What we do", ideasAfterglow: "Ideas with afterglow.", haveAGoodOne: "Have a good one?", makeSomethingLast: "Let’s make something last.", startConversation: "Start a conversation", aboutTitle: "A small studio with a wide lens.", aboutDescription: "We are a loose constellation of directors, designers, strategists, and makers.", capabilities: "Capabilities", journalTitle: "Notes from the process.", noServices: "No services have been published yet.", noProjects: "No projects have been published yet.", noPosts: "No journal posts have been published yet.", unableServices: "Unable to load services right now.", unableProjects: "Unable to load projects right now.", unablePosts: "Unable to load journal posts right now.", back: "Back", readNote: "Read note", servicesLabel: "Services", clientLabel: "Client", categoryLabel: "Category", projectNotFound: "Project not found", noteNotFound: "Note not found", serviceNotFound: "Service not found", contactName: "Name", contactEmail: "Email", contactPhone: "Phone", contactMessage: "Message", sendMessage: "Send message", sentMessage: "Message sent successfully.", adminOverview: "Overview", adminServices: "Services", adminProjects: "Projects", adminCategories: "Categories", adminJournal: "Journal", adminClients: "Clients", adminTestimonials: "Testimonials", adminMessages: "Messages", adminSettings: "Settings", adminWorkspace: "Workspace", adminContent: "Content management", adminAdd: "Add new", adminEdit: "Edit", adminSave: "Save changes", adminCreate: "Create", adminCancel: "Cancel", adminLoading: "Loading workspace…", adminEmpty: "No records yet. Create the first one to get started.", adminSignIn: "Sign in to manage your studio.", adminWelcome: "Welcome back.", adminEnter: "Enter dashboard", adminChecking: "Checking workspace access…", adminSignOut: "Sign out", adminManage: "Manage →", adminGoodMorning: "Good morning", adminInMotion: "Your studio, in motion.", adminUnauthorized: "This account is not authorized for the admin workspace.", adminRequired: "A title is required.", adminUpdated: "Record updated.", adminCreated: "Record created.", adminDeleted: "Record deleted.", adminUpload: "Attach cover image/video", adminUploading: "Uploading…", adminAttached: "Media attached", adminCloudinary: "Cloudinary upload is not configured." ,
  },
  fr: {
    brand: "PRODUCTION / PUBLICITÉ",
    work: "Projets", services: "Services", journal: "Journal", about: "À propos", contact: "Démarrer un projet",
    admin: "Admin", language: "Langue", menu: "Ouvrir le menu", footer: "Une production créative indépendante pour les marques qui veulent rester en mémoire.",
    copyright: "© 2026 Production Publicité", directionNote: "Des histoires qui vibrent.", loading: "Chargement de Production…",
    homeEyebrow: "STUDIO CRÉATIF INDÉPENDANT · 01—26", homeTitle: "Nous créons ce qui compte.",
    homeDescription: "Production est un studio créatif qui façonne films, identités et mondes numériques pour celles et ceux qui construisent demain.",
    explore: "Découvrir les projets", pointOfView: "Notre regard", scroll: "Défiler pour explorer ↓", newPerspectives: "DE NOUVELLES PERSPECTIVES, TOUJOURS", selectedWork: "Projets sélectionnés", aFewThings: "Quelques histoires que nous avons créées.", viewAll: "Voir tous les projets", whatWeDo: "Notre métier", ideasAfterglow: "Des idées qui restent.", haveAGoodOne: "On crée quelque chose de beau ?", makeSomethingLast: "Créons quelque chose qui dure.", startConversation: "Démarrer une conversation", aboutTitle: "Un petit studio avec un regard large.", aboutDescription: "Nous sommes une constellation de réalisateurs, designers, stratèges et créateurs.", capabilities: "Expertises", journalTitle: "Notes du processus.", noServices: "Aucun service n’est publié pour le moment.", noProjects: "Aucun projet n’est publié pour le moment.", noPosts: "Aucune note n’est publiée pour le moment.", unableServices: "Impossible de charger les services.", unableProjects: "Impossible de charger les projets.", unablePosts: "Impossible de charger les notes.", back: "Retour", readNote: "Lire la note", servicesLabel: "Services", clientLabel: "Client", categoryLabel: "Catégorie", projectNotFound: "Projet introuvable", noteNotFound: "Note introuvable", serviceNotFound: "Service introuvable", contactName: "Nom", contactEmail: "E-mail", contactPhone: "Téléphone", contactMessage: "Message", sendMessage: "Envoyer", sentMessage: "Message envoyé avec succès.", adminOverview: "Vue d’ensemble", adminServices: "Services", adminProjects: "Projets", adminCategories: "Catégories", adminJournal: "Journal", adminClients: "Clients", adminTestimonials: "Témoignages", adminMessages: "Messages", adminSettings: "Paramètres", adminWorkspace: "Espace de travail", adminContent: "Gestion du contenu", adminAdd: "Ajouter", adminEdit: "Modifier", adminSave: "Enregistrer", adminCreate: "Créer", adminCancel: "Annuler", adminLoading: "Chargement…", adminEmpty: "Aucun enregistrement. Créez le premier pour commencer.", adminSignIn: "Connectez-vous pour gérer votre studio.", adminWelcome: "Bon retour.", adminEnter: "Accéder au tableau de bord", adminChecking: "Vérification de l’accès…", adminSignOut: "Se déconnecter", adminManage: "Gérer →", adminGoodMorning: "Bonjour", adminInMotion: "Votre studio en mouvement.", adminUnauthorized: "Ce compte n’est pas autorisé à accéder à l’espace d’administration.", adminRequired: "Un titre est requis.", adminUpdated: "Enregistrement mis à jour.", adminCreated: "Enregistrement créé.", adminDeleted: "Enregistrement supprimé.", adminUpload: "Joindre une image/vidéo", adminUploading: "Téléversement…", adminAttached: "Média joint", adminCloudinary: "L’upload Cloudinary n’est pas configuré.",
  },
  ar: {
    brand: "إنتاج / دعاية وإشهار",
    work: "الأعمال", services: "الخدمات", journal: "المجلة", about: "من نحن", contact: "ابدأ مشروعًا",
    admin: "الإدارة", language: "اللغة", menu: "فتح القائمة", footer: "إنتاج إبداعي مستقل للعلامات التي تريد أن تبقى في الذاكرة.",
    copyright: "© 2026 إنتاج للدعاية والإشهار", directionNote: "حكايات نابضة بالحياة.", loading: "جارٍ تحميل إنتاج…",
    homeEyebrow: "استوديو إبداعي مستقل · ٠١—٢٦", homeTitle: "نصنع ما يترك أثرًا.",
    homeDescription: "إنتاج استوديو إبداعي يصوغ الأفلام والهويات والعوالم الرقمية لمن يبنون الخطوة التالية.",
    explore: "اكتشف أعمالنا", pointOfView: "رؤيتنا", scroll: "مرّر للاستكشاف ↓", newPerspectives: "آفاق جديدة دائمًا", selectedWork: "أعمال مختارة", aFewThings: "أشياء صنعناها وتستحق أن تُروى.", viewAll: "شاهد كل الأعمال", whatWeDo: "ماذا نصنع", ideasAfterglow: "أفكار تترك أثرًا.", haveAGoodOne: "هل لديك فكرة؟", makeSomethingLast: "لنصنع شيئًا يدوم.", startConversation: "ابدأ محادثة", aboutTitle: "استوديو صغير بعدسة واسعة.", aboutDescription: "نحن شبكة من المخرجين والمصممين والاستراتيجيين والصنّاع.", capabilities: "قدراتنا", journalTitle: "ملاحظات من الرحلة.", noServices: "لم تُنشر خدمات بعد.", noProjects: "لم تُنشر مشاريع بعد.", noPosts: "لم تُنشر مقالات بعد.", unableServices: "تعذر تحميل الخدمات حاليًا.", unableProjects: "تعذر تحميل المشاريع حاليًا.", unablePosts: "تعذر تحميل المقالات حاليًا.", back: "رجوع", readNote: "اقرأ المقال", servicesLabel: "الخدمات", clientLabel: "العميل", categoryLabel: "التصنيف", projectNotFound: "المشروع غير موجود", noteNotFound: "المقال غير موجود", serviceNotFound: "الخدمة غير موجودة", contactName: "الاسم", contactEmail: "البريد الإلكتروني", contactPhone: "الهاتف", contactMessage: "الرسالة", sendMessage: "إرسال الرسالة", sentMessage: "تم إرسال الرسالة بنجاح.", adminOverview: "نظرة عامة", adminServices: "الخدمات", adminProjects: "المشاريع", adminCategories: "التصنيفات", adminJournal: "المجلة", adminClients: "العملاء", adminTestimonials: "الشهادات", adminMessages: "الرسائل", adminSettings: "الإعدادات", adminWorkspace: "مساحة العمل", adminContent: "إدارة المحتوى", adminAdd: "إضافة", adminEdit: "تعديل", adminSave: "حفظ التغييرات", adminCreate: "إنشاء", adminCancel: "إلغاء", adminLoading: "جارٍ التحميل…", adminEmpty: "لا توجد سجلات بعد. أنشئ أول سجل للبدء.", adminSignIn: "سجّل الدخول لإدارة منصتك.", adminWelcome: "مرحبًا بعودتك.", adminEnter: "دخول إلى لوحة التحكم", adminChecking: "جارٍ التحقق من صلاحية الوصول…", adminSignOut: "تسجيل الخروج", adminManage: "إدارة ←", adminGoodMorning: "صباح الخير", adminInMotion: "استوديوك في حركة.", adminUnauthorized: "هذا الحساب غير مخول للوصول إلى مساحة الإدارة.", adminRequired: "العنوان مطلوب.", adminUpdated: "تم تحديث السجل.", adminCreated: "تم إنشاء السجل.", adminDeleted: "تم حذف السجل.", adminUpload: "إرفاق صورة/فيديو", adminUploading: "جارٍ الرفع…", adminAttached: "تم إرفاق الوسيط", adminCloudinary: "لم يتم إعداد رفع Cloudinary.",
  },
} as const;

const LanguageContext = createContext<{ locale: Locale; setLocale: (locale: Locale) => void; t: (key: TranslationKey) => string }>({
  locale: "en", setLocale: () => undefined, t: key => translations.en[key],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(() => (localStorage.getItem("production-locale") as Locale) || "ar");
  const setLocale = (next: Locale) => { setLocaleState(next); localStorage.setItem("production-locale", next); };
  useEffect(() => { document.documentElement.lang = locale; document.documentElement.dir = locale === "ar" ? "rtl" : "ltr"; }, [locale]);
  const value = useMemo(() => ({ locale, setLocale, t: (key: TranslationKey) => translations[locale][key] }), [locale]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() { return useContext(LanguageContext); }
export type { TranslationKey };
